# Generated by Django 4.2 on 2023-05-03 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=150, verbose_name='Заголоков')),
                ('news_text', models.TextField(verbose_name='Текст новости')),
                ('news_relize_date', models.DateField(default=datetime.date(2023, 5, 3), verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст коментария')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.TextField(verbose_name='Текст тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterModelOptions(
            name='newsauthor',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='news',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.newscategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.newscomment', verbose_name='Коментарии'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.newsauthor', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsPortal.newstag', verbose_name='Теги'),
        ),
    ]
