# Generated by Django 4.2.1 on 2023-05-04 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_news_newscategory_newscomment_newstag_delete_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_relize_date',
            field=models.DateField(default=datetime.date(2023, 5, 4), verbose_name='Дата выпуска'),
        ),
    ]
