# Generated by Django 4.1.5 on 2023-05-11 04:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0003_alter_news_news_relize_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='id_news',
            field=models.TextField(default=1, verbose_name='Новость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='NewsPortal.newscategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='NewsPortal.newscomment', verbose_name='Коментарии'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='NewsPortal.newsauthor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_relize_date',
            field=models.DateField(default=datetime.date(2023, 5, 11), verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='NewsPortal.newstag', verbose_name='Теги'),
        ),
    ]
