# Generated by Django 4.1.5 on 2023-05-12 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0005_remove_news_comment_alter_newscomment_id_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_relize_date',
            field=models.DateField(default=datetime.date(2023, 5, 12), verbose_name='Дата выпуска'),
        ),
    ]
