# Generated by Django 4.1.5 on 2023-05-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0006_alter_news_news_relize_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='NewsPortal.newscategory', verbose_name='Категория'),
        ),
    ]
